//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientSupplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientSupplier()
        {
            this.ClientSupplier1 = new HashSet<ClientSupplier>();
        }
    
        public int ClientID { get; set; }
        public int ContactID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ParentClientID { get; set; }
        public double DefaultRecoveryRate { get; set; }
        public string Notes { get; set; }
        public int OfficeID { get; set; }
        public int DepartmentID { get; set; }
        public string ClientCode { get; set; }
        public Nullable<System.DateTime> PeriodEndDate { get; set; }
        public bool Vattable { get; set; }
        public int CliFileID { get; set; }
        public bool Internal { get; set; }
        public byte ClientVATTypeID { get; set; }
        public Nullable<int> ZID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> DefaultCurrency { get; set; }
        public byte ClientSupplierType { get; set; }
        public Nullable<byte> TermsTypeID { get; set; }
        public Nullable<short> TermsDay { get; set; }
        public Nullable<short> PaymentTypeID { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public Nullable<short> DefaultNominalID { get; set; }
        public Nullable<short> AccountStatusID { get; set; }
        public string BankAccountName { get; set; }
        public string BankAccountNum { get; set; }
        public string BankSortCode { get; set; }
        public string BACSRef { get; set; }
        public Nullable<int> ApprovalEmpID { get; set; }
        public Nullable<int> DefaultContactAssoc { get; set; }
        public Nullable<System.DateTime> Closed { get; set; }
        public string CompanyRegistrationNo { get; set; }
        public string CompanyTaxReference { get; set; }
        public System.Guid RowGuid { get; set; }
        public Nullable<int> ClientClosedReasonId { get; set; }
        public bool Draft { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<int> ReasonWonId { get; set; }
    
        public virtual ClientVATType ClientVATType { get; set; }
        public virtual ClientSupplierType ClientSupplierType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientSupplier> ClientSupplier1 { get; set; }
        public virtual ClientSupplier ClientSupplier2 { get; set; }
    }
}
