//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientVATType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientVATType()
        {
            this.ClientSuppliers = new HashSet<ClientSupplier>();
        }
    
        public byte ClientVATTypeID { get; set; }
        public string ShortName { get; set; }
        public string LongName { get; set; }
        public Nullable<int> VatRateId { get; set; }
        public decimal DiscountMultiplier { get; set; }
        public byte ClientSupplierType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientSupplier> ClientSuppliers { get; set; }
        public virtual ClientSupplierType ClientSupplierType1 { get; set; }
    }
}
